### ISSUE TITLE
Roadmap - Developer Preview #2

### ISSUE THREAD

**Issue by sigilante** [zorp-corp/jock-lang#9]
## Developer Preview \#2 (DP2)

DP2 is the next alpha release of Zorp's Jock language.  (We call the October 2024 developer preview alpha DP1.)  DP2 will allow developers to write Nock programs utilizing the Hoon standard library.  Since the target Nock ISA will not change, programs produced with Jock DP2 will still be functional in the future even if syntax changes.

Our objective with Jock DP2 is to obtain developer feedback on syntax and affordances, as well as start to grow a user community interested in working with Nockchain or on the Zorp zkVM.

### Punch List

- [x] Hoon-based testing of AST and Nock generation #11
- [x] finish `match type`/`match case` keyword (with unit testing) #7
- [x] implement recursive types, starting with `List` #19 
- [x] `List` and `Set` type declaration #20
- [x] Improved `List`/`Set` syntax #21
- [x] native syntax for map/set #21
- [x] general type declaration (`+$`) → `class` #26
  - [x] implement constructor as `new` #26
  - [x] fix method syntax #37
  - [x] change constructor to `load` #37
  - [x] fix state refs #49
- [x] upgrade testing to `.*` #36
- [x] rename `match case` to `switch` #33
- [x] flip wing syntax to left-to-right #35
- [x] infix operators #38
- [x] Hoon FFI/RPC interface #39
  - [x] stdlib basics #39
- [x] make tests real (currently `{}` breaks them in many cases)
- [x] QoL issues
  - [x] `$()` syntax #45
  - [x] string parsing #46
- [x] generalize container type implementation #40
- [x] `class` checklist
  - [x] expose state as legs #50
  - [x] allow iterated evaluation on instances #50
- [ ] prepare release materials
  - [x] finish DP2 docs and tutorial
  - [ ] ~~make at least one JockApp demo~~ deferred for type reasons
  - [x] flesh out some simple branding (Platform font, orange color good basis)
  - [ ] update website for release announcement
  - [ ] make a teaser video for @ZorpZK and @Nockchain accounts to plug
- [ ] Nice to haves:
  - [ ] prettyprinter with `print` keyword #53
  - [ ] list index syntax
  - [x] arbitrary import #55, #56
  - [x] switch to snake case (so `x-1` is an expression rather than a name) #57

### Future Plans (Nonblocking)

These are concepts that we intend to implement moving forward from DP2's release.

- [x] value injection (e.g. from `choo` CLI)
  - [x] convert to input `map` like libs from #55
- [ ] `Map` native syntax
- [ ] fix `Set` ordering
- [ ] proper Hoon stdlib return jype
- [ ] ~~`/~` directory import with `choo`~~ (superseded by #55)
- [x] `slog` printing side effect #53
- [ ] `class` native implementation of `List`/`Set`/`Map`
- [ ] invoke w/i function by name (recurse)
- [ ] traits/templates → `protocol`
  - [ ] core polymorphism
- [ ] optimize Nock compilation a bit more [like Hoon](https://github.com/urbit/urbit/blob/a3d96d3aa0c321f9833bd360eb800f07c87b8e72/pkg/arvo/sys/hoon.hoon#L7267-L7372)
- [ ] event loop NockApp (JockApp)
- [ ] crash handling with line numbers
- [x] `import` support #39
- [ ] REPL (event loop + NockApp)
- [ ] change operator associativity to left-to-right (intuitive) direction
- [ ] gate-building gate call syntax (`sane('tas'; %test)`)
- [ ] posit floating-point support

**Comment by sigilante** [comment]
Possible gate-building gate syntaxes:

- `sane[%tas, %test]`
- `sane('tas'; %test)`
- `sane(%tas, %test)`

**Comment by sigilante** [comment]
Perhaps `(map path cord)` instead of `(map term cord)`.
